In [2]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_ncbi1.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df1 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df1

         description                                           sequence
0     WP_008253902.1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1     WP_014164161.1  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2     WP_014164206.1  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
3     WP_014164231.1  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
4     WP_014164268.1  MPKMKTKSSAKKRFKVTGSGKIKRKHAFKSHILTKKSKKRKLALTH...
...              ...                                                ...
2712  WP_256380912.1  MDLEFHNNFITFLEKKQQLNNNTIGGYIDDIKLFCNTAEREGLNTS...
2713  WP_256380913.1  MYGKTRKIEGDQNLIPFLYQGQYYDHDIELAYNRFRYYNPETGTYI...
2714  WP_256380914.1  MYGGLRNFSSPINLTPDFIPFRQIGQYEDPELEGLYYNRFRYYDCT...
2715  WP_269465228.1  MYGKTRKIEGDQNLIPFLYQGQYYDHDIELAYNRFRYYNPETGTYI...
2716  WP_269465229.1  MYGKTRKIEGDQNLIPFLYQGQYYDHDIELAYNRFRYYNPETGLYL...

[2717 rows x 2 columns]

In [3]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_ncbi2.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df2 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df2

         description                                           sequence
0     WP_008253902.1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1     WP_014164156.1  MSELLLKPEERYASIIEQRRNEDGSELAILNLGPTHPATHGIFQNI...
2     WP_014164161.1  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
3     WP_014164206.1  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
4     WP_014164219.1  MINLKIGDKAPDFSVVDENGNLHELKKYNGKKIVLFFYPKANTPGC...
...              ...                                                ...
2651  WP_256366390.1          MEKETETLDIIEPRIITEELIISYVAKFFDNLTRWQNLERN
2652  WP_256366392.1  MGLGGGIGSILRYLASLFFNRFVISGFPTGTFMVNSIGCFLIGLFF...
2653  WP_256366393.1  MKRYFTNSFGFMDGGLDLHISETLGWHIEENLQKQIAQLDEKELLI...
2654  WP_256366394.1  MLGNRNSYSKTDPDATFMRMKEDHMRNGQLKPTYNPQISIENQFIT...
2655  WP_269465534.1  MYGKTRKIEGDQNLIPFLYQGQYYDHDIELAYNLFRYYNPETGTYI...

[2656 rows x 2 columns]

In [4]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_ncbi3.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df3 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df3

         description                                           sequence
0     WP_008253902.1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1     WP_014164159.1  MKVTIDGQSIEVEPGTTILQAARMIGGESVPPAMCYYSKLEKTGGK...
2     WP_014164161.1  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
3     WP_014164206.1  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
4     WP_014164231.1  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
...              ...                                                ...
2654  WP_262494541.1       MKELNVYEQKTQEIYSALKGLNLKTAEQILQRVSKELQISSIVS
2655  WP_262494544.1  MGLGGGIGSILRYLASLFFNRFVISGFPTGTFMVNSIGCFLIGLFF...
2656  WP_262494545.1       MDYYQKANSSDINPDFERKSYTQKQWRIIQEKGVEITVLKTITQ
2657  WP_262494546.1  VYSPEFILLDKEKVDYLHTKNIKVIPWTVNKKEDMQTIMSYGVDGL...
2658  WP_262494548.1  MALILKQIATALSCEFIEVDSSIVIDTVSVDSRSHQNANSTLFFAL...

[2659 rows x 2 columns]

In [5]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_ncbi4.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df4 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df4

         description                                           sequence
0     WP_008253902.1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1     WP_014164159.1  MKVTIDGQSIEVEPGTTILQAARMIGGESVPPAMCYYSKLEKTGGK...
2     WP_014164161.1  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
3     WP_014164206.1  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
4     WP_014164231.1  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
...              ...                                                ...
2689  WP_256380911.1  MLGNRNSYSKTDPDATFMRMKEDHMRNGQLKPAYNPQISIENQFIT...
2690  WP_262494474.1        MKDLFIRGYLERISKQFEISIDDAFEVFSIAVVLDKSFDEVYK
2691  WP_262494475.1  MKRYFTNSFGFMDGGLDLHISETLGWHIEENLQKQIAQLDEKELLI...
2692  WP_262494476.1       MKESNVYEQKVQEIYSALKGLNLKKAEQILQRVSKELQFSSIVS
2693  WP_262494497.1          MPFTRQEIANFTGLRVETVIRACSKLKKTGIIEIINHKIYF

[2694 rows x 2 columns]

In [6]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_ncbi5.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df5 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df5

         description                                           sequence
0     WP_008253902.1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1     WP_014164161.1  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2     WP_014164231.1  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
3     WP_014164260.1  MKFELLHTDPQTQARAGKVITDHGVIETPIFMPVGTVASVKGVHQR...
4     WP_014164268.1  MPKMKTKSSAKKRFKVTGSGKIKRKHAFKSHILTKKSKKRKLALTH...
...              ...                                                ...
2275  WP_235876606.1  MQDENDISKIILDCAYKVHTKLGSGLLEKVYRECLAYELEKCGLNV...
2276  WP_235876608.1  MNSASNKGELNFASNKGELNSASNKGELNFASNKGELDFALSTGEL...
2277  WP_235876610.1  MVTRVPSGFFTLFSILLAINKTLKYQYLYQLHIENTLQLYNTFPQI...
2278  WP_235876611.1  MVIRVPSGFFTLFSILLAINKTLKYQYLYQLHIENTLQLYNTFPQI...
2279  WP_235876613.1  MVTRVPSGFFTLFSILLAINKTLKYQYLYQLHIENTLQLYNTFPQI...

[2280 rows x 2 columns]

In [7]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_ncbi6.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df6 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df6

         description                                           sequence
0     WP_008253902.1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1     WP_014164161.1  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2     WP_014164206.1  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
3     WP_014164231.1  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
4     WP_014164260.1  MKFELLHTDPQTQARAGKVITDHGVIETPIFMPVGTVASVKGVHQR...
...              ...                                                ...
2531  WP_262914961.1        MKDLFIRGYLEKISKQFEISIDDAFEVFSIAVVLDKSFDEVYK
2532  WP_262914962.1  MQFVNQTHRSVFLTGKAGTGKTTLLKEIIATSHKNTAIVAPTGIAA...
2533  WP_262914963.1  MSFVIEALFQKTDKSFLLLANEKEEAAYLLNDLEHLIGEKEVLFYP...
2534  WP_262914964.1  INNSGFNFPTAYNIGGANDVSYIGSGQDMHIANANNTKSIIFSTGT...
2535  WP_262914965.1  TYISQDPIRLLGGNPNLYAYVKNTNAWIDIFGLDCKVKVTAGDGVT...

[2536 rows x 2 columns]

In [8]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_ncbi7.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df7 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df7

         description                                           sequence
0     WP_008253902.1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1     WP_014164161.1  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2     WP_014164206.1  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
3     WP_014164231.1  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
4     WP_014164268.1  MPKMKTKSSAKKRFKVTGSGKIKRKHAFKSHILTKKSKKRKLALTH...
...              ...                                                ...
2641  WP_279573986.1  ELAYNRFRYYNPETGLYLSQDPIRLLGGNPNLYAYVKNTNAWIDIF...
2642  WP_279573987.1  EGNNPTFYAYVHDSNSWVDPFGLELEPTVNLGTAPKGTTLYHYTNA...
2643  WP_279573990.1  MVEKIPKTFRHKFRSLIFLICLTTLFFLPVQKSYSQCGTGFQQGGF...
2644  WP_279573991.1  ELAYNRFRYYNPETGTYISQDPIGLLGGNELYAYVKNSNIQIDKFG...
2645  WP_279573992.1  INNSGFNFPTAYNIGGANDVSYIGSGQDMHIANANNTKSIIFSTGT...

[2646 rows x 2 columns]

In [9]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new1.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df8 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df8

,description,sequence
0,fig|6666666.1036451.peg.3386,RVNNHPMYAICERMYVEEGLNKKAIANATGVSEQTIGKWSKGVGES...
1,fig|6666666.1036451.peg.3387,MAEKLNKNIEKLLASYEEHCKKIKQIKNVNVNETPQERRKKRLELE...
2,fig|6666666.1036451.peg.3388,MGFILEEDYSVLIRNEIKDILLENYSPQKLSIAQDMAISQIKNYLS...
3,fig|6666666.1036451.peg.3389,MKVLGFEFSVKKNKVSAIQEKTRTNTNPAILNIVSSFKDNSRKDIK...
4,fig|6666666.1036451.peg.3390,MLLELAEASVGTFPYGTEIKFNEANRTDAFRVYKEFIQSNAEVVSK...
...,...,...
3426,fig|6666666.1036451.peg.3322,MNIVSSFKDNSRKDIKKWRDALAMANHPKEPKLNLYYDLLDDLLTD...
3427,fig|6666666.1036451.peg.3323,MLLELAEASVGTFPYGTEIKFNEANRTDAFRVYKEFIQSNAEVVSK...
3428,fig|6666666.1036451.peg.3324,MANKCGCEPLALGKSISTLLDALCKELALSLWNGKETKGILGRMIQ...
3429,fig|6666666.1036451.peg.3325,MTFDKYNLKLYQDFKDSLKAIELDGTITPKNVKELFKKEKDTNYMG...
3430,fig|6666666.1036451.peg.3326,MASAKLTMLLDLSDKVSSKFASIQNKFNRGASRMRESFSEITAEIP...

In [10]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new2.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df9 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df9

,description,sequence
0,fig|6666666.1036453.peg.69,MVCFWRKTDNDQYKTLGIKTKSEFYNVCAELIQPLNLEGLSVSSGA...
1,fig|6666666.1036453.peg.70,MQVGKHKLVDTETGEIINVDIHQAVMFYAFMAVGQGTKLNMRQQYE...
2,fig|6666666.1036453.peg.71,MRTRCIVPMVQELSITDITTRKKKKTRKLYVMLITDVASSKIVGWS...
3,fig|6666666.1036453.peg.72,MVFNKVRNIQAGNSQANPAELQFKLFKNSLRGLSNFGSTSWGVSIE...
4,fig|6666666.1036453.peg.73,MTKLNNFQKTKQIPDAIRMYLVEKNTNQANLAKLSGVGEAYVSTIL...
...,...,...
3439,fig|6666666.1036453.peg.3440,MTTEGKAIGLQILEKQPELKAVFLTVEGEYFTCKDWAMNGTKEKDK...
3440,fig|6666666.1036453.peg.3441,MADLKGFNLQKGKQGASILDNSEGVTALVVSSPVPQGMEHQKSFVI...
3441,fig|6666666.1036453.peg.3442,MADLIRNSKAYDSADVKVQINGVPIEVKSISYGNEQEHQLNHSLGA...
3442,fig|6666666.1036453.peg.3443,MSHTENQENKETIQKVAEETISSLKIEHGQDLRKLTLPANEDETKF...
3443,fig|6666666.1036453.peg.3444,MDDGASILINLAMRYATAFGVAFQSKAVVVKEDNKYKVEYYDKQSE...

In [11]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new3.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df10 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df10

,description,sequence
0,fig|6666666.1036455.peg.1,KDLSDKTTELNSLKSATQKKEVEDLIAKGKADKKLTVELANTLLAD...
1,fig|6666666.1036455.peg.2,MANPKIPQEFWNSYIVEKLRRTNPHLNLCFDESAHVVGGAVVYIPQ...
2,fig|6666666.1036455.peg.3,MDNAVKAVKYYRELLDDMAKRLAEATEALMKLEEKHHDLMRINQSL...
3,fig|6666666.1036455.peg.4,MITSTDCTKAFGKPDIDFEIKYMVVWKVPEAIRVKIPVLPQKIYCH...
4,fig|6666666.1036455.peg.5,MKNISLFRVVLFAMLVGIMGACKSSLAPTVTSQTNDTIIKVQTLRD...
...,...,...
2990,fig|6666666.1036455.peg.2991,MDGGTTFKNILFEKCPPLRSCNGVVIYADPAPSDSELKQSSSKAVV...
2991,fig|6666666.1036455.peg.2992,MAKKKISNKAYLDLWKQFSANMDNATPIDLSESHSDKLKRIKHLEA...
2992,fig|6666666.1036455.peg.2993,MGIQKKEEREYARILYVNERITYKEIASRVKVTEKTVSKWAEEDNW...
2993,fig|6666666.1036455.peg.2994,MQSLPVNFQGFATICKFASTKKRKVEKAKKIDKEFCLTDDSVNVYG...
2994,fig|6666666.1036455.peg.2995,MANPKIPQEFWNSYIVEKLRRTNPHLNLCFDESAHVVGGAVVYIPQ...

In [12]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new4.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df11 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df11

,description,sequence
0,fig|6666666.1036461.peg.65,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...
1,fig|6666666.1036461.peg.66,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
2,fig|6666666.1036461.peg.67,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSILPNS...
3,fig|6666666.1036461.peg.68,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
4,fig|6666666.1036461.peg.69,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
...,...,...
3335,fig|6666666.1036461.peg.41,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...
3336,fig|6666666.1036461.peg.42,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
3337,fig|6666666.1036461.peg.43,MSGPIRHLTILQSPVFLINSRPDLFTAASLRWRPFSRSYRSILPNS...
3338,fig|6666666.1036461.peg.44,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
3339,fig|6666666.1036461.peg.45,MFLAPLIVTYAYIFFNFSSISHKTPSAMLECSPTTCTVYKSIASVV...

In [13]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new5.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df12 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df12

,description,sequence
0,fig|6666666.1036416.peg.1489,MGYNGAYGCYKMFTKGQVQRMYKALHHSSRKKLWQKENLVVTGLLQ...
1,fig|6666666.1036416.peg.1490,MITQTIKPNVAIVTDVCHDTTTPMIDKKIEGDLKIGRGPVIAYAPA...
2,fig|6666666.1036416.peg.1491,MSTETILNDLSISFLERYLNNASPTGYESEGQKIWMDYLKSYVDTF...
3,fig|6666666.1036416.peg.1492,MYKYNITLVFLFLSMFTITAQEVKIDSTEIEKKLDIKDTIAQVSYQ...
4,fig|6666666.1036416.peg.1493,MVLKRRVMRTYPYAKIAADRLVALNNGMKLLKTERDKKIF
...,...,...
3264,fig|6666666.1036416.peg.2605,MVSGSFSLRYSRFFSPFPHGTGSLSVSQEYLALADGPARFRQGFSC...
3265,fig|6666666.1036416.peg.2606,MTKNASFLTLLFFCFNIAIKTCCQSNMSMNLFLLFFAFDLLS
3266,fig|6666666.1036416.peg.2607,MFFPSLFFAFFVFCFLVAVFQIFNFVFYLFWIVLGFLFVILGRVWY
3267,fig|6666666.1036416.peg.2608,MSVPLRVGLSVLSFAERTIPIKKSHTNQQKDDTSIPHASLASNKKK...
3268,fig|6666666.1036416.peg.2609,MIKITLPDGSIREYASGVTPMDVAKSISEGLARNVISASFNGTTVE...

In [14]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new6.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df13 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df13

,description,sequence
0,fig|6666666.1036462.peg.2435,KVLNPKYARLGDGQYFSNIVPGTKNSKQLAASFVRVPNPHLFTHYI...
1,fig|6666666.1036462.peg.2436,MRYYKIEWIHKNNEEYPYLYILEVNTLGEEIKKMEFYTDGRINYAT...
2,fig|6666666.1036462.peg.2437,MSLADNIKNIREQKNFKQIEVANYIGVDKSAYSKIEKGTRSLAVEE...
3,fig|6666666.1036462.peg.2438,MDIQDIKQTLSLSQVLQHYNLQPNKNKMLCCPFHDDKTASLQVNLQ...
4,fig|6666666.1036462.peg.2439,MIHKASYKEELLILGYHKLSVEQRIRNIHHFIRITQKELQQVKPSD...
...,...,...
3223,fig|6666666.1036462.peg.3149,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSYFA
3224,fig|6666666.1036462.peg.3150,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
3225,fig|6666666.1036462.peg.3151,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASG...
3226,fig|6666666.1036462.peg.3152,MVSGSFSLRYSRFFSPFPHGTGSLSVSQEYLALADGPARFRQGFSC...
3227,fig|6666666.1036462.peg.3153,MWSYNPVIAVTTTVWAIPRSLATTYGITFVFFSSAYLDVSVQRVCL...

In [15]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new7.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df14 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df14

,description,sequence
0,fig|6666666.1036429.peg.2203,MWSYNPVIAVTTTVWAIPRSLATTYGITFVFFSSAYLDVSVQRVCL...
1,fig|6666666.1036429.peg.2204,MVSGSFSLRYSRFFSPFPHGTGSLSVSQEYLALADGPARFRQGFSC...
2,fig|6666666.1036429.peg.2205,MFLAPLIVTYAYIFFSNLSSIPHETPSAMLECSPTTCTVYKSIASV...
3,fig|6666666.1036429.peg.2206,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
4,fig|6666666.1036429.peg.2207,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSILPNS...
...,...,...
3220,fig|6666666.1036429.peg.1861,MSKQIINKPLCLEKVAKGRLTDSCLLVRSKDNIIKEIDVKDLKDLN...
3221,fig|6666666.1036429.peg.1862,MMKAIFKNWKTTSAGVVSIVSGVLLFVNDKTKTIEALTAVLAGIGL...
3222,fig|6666666.1036429.peg.1863,MKKVFTSAPLPFMGQKRKFLKQFKPALNEFPADAIYVDLFGGSGLL...
3223,fig|6666666.1036429.peg.1864,MLDDIRIILVNHPKDKIIKGEAREQVLERIRLEVTKGYVDYITISS...
3224,fig|6666666.1036429.peg.1865,MKNENTINLRLRFYKDIDETVEGVRQKFIDYKSQISPDYVMKIRRN...

In [16]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new8.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df15 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df15

,description,sequence
0,fig|6666666.1036430.peg.768,YVDREKAKSKRGKIGIEHANIKDIQEALMHVSSPLEEAKETIDKSV...
1,fig|6666666.1036430.peg.769,MEYKDIATPSRTRALLDQYGFNFKKSLGQNFLIDVNIINKIIEASH...
2,fig|6666666.1036430.peg.770,MPKSILDIKNSIDCHLGNRIVLKANGGRKKTIERSGVLKETYPSVF...
3,fig|6666666.1036430.peg.771,MIYETAPAKINFTLDTLFKRDDGYHEIEMVMTTVDLNDRLSFEKRT...
4,fig|6666666.1036430.peg.772,MRYKRSERIVFMTQYLMNHPNKLIPLTYFVKKFKQAKSSISEDVQI...
...,...,...
3491,fig|6666666.1036430.peg.839,MKIQDYTKEMVDEKSFIDMAYTLLNDKQTTMNLYDIIDEFKSLGGY...
3492,fig|6666666.1036430.peg.840,MFIKKDFDDITVQVFEEKYRDALNQFELSERQQIYSSLPQTVLDDA...
3493,fig|6666666.1036430.peg.841,MKIGIDAGGTLIKIVQEHDNRRYYRTELTTNIQKVIDWLNNEEIET...
3494,fig|6666666.1036430.peg.842,MSYKYEAFFKDILINEYIYFASKNKKLIRIQHENLPYIAMWTDENV...
3495,fig|6666666.1036430.peg.843,IVHEASVTNKLEQLFKIVGREIPPHIYKFKDQETYESLIRNLALHH...

In [17]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new9.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df16 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df16

,description,sequence
0,fig|6666666.1036463.peg.1,MHTRYAPVRRSQRSKLLLPLDLHVLSLPLAFIKSQDQTLHRMFFIA...
1,fig|6666666.1036463.peg.2,MKEISSCGGFRAYMLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLV...
2,fig|6666666.1036463.peg.3,MRWRPFSRSYRSILPNSLAMNLSSALGYSPQLPVSVYGTGTYNLCL...
3,fig|6666666.1036463.peg.4,MAAFRYSIPLSEDSEYYRISPVPADLPTGTIVRCFNELFRQFAVLS...
4,fig|6666666.1036463.peg.5,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
...,...,...
3397,fig|6666666.1036463.peg.3369,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
3398,fig|6666666.1036463.peg.3370,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...
3399,fig|6666666.1036463.peg.3371,MRWRPFSRSYRSILPNSLAMNLSSALGYSPQLPVSVYGTGTYNLCL...
3400,fig|6666666.1036463.peg.3372,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
3401,fig|6666666.1036463.peg.3373,PAKQGDFLSQQKNIWFLLLKKTKENKKLSKKSKKTLGNTKRNTTFA...

In [18]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new10.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df17 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df17

,description,sequence
0,fig|6666666.1036468.peg.5254,MVSGSFSLRYSRFFSPFPHGTGSLSVSQEYLALADGPARFRQGFSC...
1,fig|6666666.1036468.peg.5255,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
2,fig|6666666.1036468.peg.5256,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
3,fig|6666666.1036468.peg.5257,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSILPNS...
4,fig|6666666.1036468.peg.5258,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
...,...,...
5453,fig|6666666.1036468.peg.3783,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
5454,fig|6666666.1036468.peg.3784,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSILPNS...
5455,fig|6666666.1036468.peg.3785,MPTGPIVRCFNELFRQFAVLSPLRRSITIISSTGILTRWPSTVPFG...
5456,fig|6666666.1036468.peg.3786,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
5457,fig|6666666.1036468.peg.3787,MVSGSFSLRYSRFFSPFPHGTGSLSVSQEYLALADGPARFRQGFSC...

In [19]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new11.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df18 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df18

,description,sequence
0,fig|6666666.1036478.peg.1718,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...
1,fig|6666666.1036478.peg.1719,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
2,fig|6666666.1036478.peg.1720,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSILPNS...
3,fig|6666666.1036478.peg.1721,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
4,fig|6666666.1036478.peg.1722,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
...,...,...
3436,fig|6666666.1036478.peg.21,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
3437,fig|6666666.1036478.peg.22,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
3438,fig|6666666.1036478.peg.23,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSILPNS...
3439,fig|6666666.1036478.peg.24,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
3440,fig|6666666.1036478.peg.25,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...

In [20]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new12.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df19 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df19

,description,sequence
0,fig|6666666.1036439.peg.29,MHLQCIGLPHWDIYGSIRVPIPVAFRSLSRPSSPLRA
1,fig|6666666.1036439.peg.30,MDAGLHRLPIPDKLRMLYNIHSSEGLGAKVQVREGKNPDHQLRSPNVC
2,fig|6666666.1036439.peg.31,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
3,fig|6666666.1036439.peg.32,MSGPIRHLTILQSPVFLINSRLDLFTAASLRWRPFSRSYRSILPNS...
4,fig|6666666.1036439.peg.33,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
...,...,...
3695,fig|6666666.1036439.peg.1170,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
3696,fig|6666666.1036439.peg.1171,MFLAPLIVTYAYIFFSNFSSISHKTPSAMLECSPTTCTVYKSIASV...
3697,fig|6666666.1036439.peg.1172,MVELYRGRATDWMRGLHRLPIPDKLRMLYNIHSSEGLGAKVQVREG...
3698,fig|6666666.1036439.peg.1173,MWSYNPVIAVTTTVWAIPRSLATTYGITFVFFSSAYLDVSVQRVCL...
3699,fig|6666666.1036439.peg.1174,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...

In [21]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new13.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df20 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df20

,description,sequence
0,fig|6666666.1036441.peg.946,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...
1,fig|6666666.1036441.peg.947,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
2,fig|6666666.1036441.peg.948,MPNSLAMNLSSALGYSPQLPVSVYGTGTYNLCLEGFLGSL
3,fig|6666666.1036441.peg.949,MSVPLRVGLSVLSFAERTIPIKKSHTNQQKDDTSIPHASLASNKKK...
4,fig|6666666.1036441.peg.950,MYKYNITLVFLFLSMFTITAQEVKIDSTEIEKKLDIKDTIAQVSYQ...
...,...,...
3068,fig|6666666.1036441.peg.941,MVYKLVFKNTFLFLLLTIVVCGNCKNKTEEREYKKFFIREFTTSFD...
3069,fig|6666666.1036441.peg.942,MNLEFFIADRLIRTKERKSNISAPIIKIAIAAIAIGLVMMIVSVAT...
3070,fig|6666666.1036441.peg.943,MPNSLAMNLSSALGYSPQLPVSVYGTGTYNLCLEGFLGSL
3071,fig|6666666.1036441.peg.944,MTPQRLATPFHSLPPILHITYPRPILSYSKGAQGLFVPLRVIGIFT...
3072,fig|6666666.1036441.peg.945,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...

In [22]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new14.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df21 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df21

,description,sequence
0,fig|6666666.1036479.peg.2500,WGNVIGVGILFIQQKLGIIKLNRINY
1,fig|6666666.1036479.peg.2501,MSFFAFFVFCFLVAVFQIFNFVFYLFWIVLGFLFCYFGSSSVLKNE...
2,fig|6666666.1036479.peg.2502,MLLQPLVGVWFQVLFHSVIHGSFSPFPHGTGSLSVSQEYLAFSGSS...
3,fig|6666666.1036479.peg.2503,MAAFRYSIPLSENSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
4,fig|6666666.1036479.peg.2504,MPNSLAMNLSSALGYSPQLPVSVYGTGTYHLCLEGFLGSL
...,...,...
3252,fig|6666666.1036479.peg.2495,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...
3253,fig|6666666.1036479.peg.2496,MWSYNPVIAVTTTVWAIPRSLATTYGITFVFFSSAYLDVSVQRVCL...
3254,fig|6666666.1036479.peg.2497,MAAFRYSIPLSEDSEYYRISPVPADLPTGPIVRCFNELFRQFAVLS...
3255,fig|6666666.1036479.peg.2498,MPNSLAMNLSSALGYSPQLPVSVYGTGTYNLCLEGFLGSL
3256,fig|6666666.1036479.peg.2499,MLSALIPSQRSYSAVLLAEQQIHQRLVQLGPLVLESDPLKFLTPTV...

In [23]:
"""
Read fasta file into Dataframe
"""

import pandas as pd
from Bio import SeqIO

# Read the fasta file
records = list(SeqIO.parse("FCovae_new15.faa", "fasta"))

# Prepare the lists to store the data
descriptions = []
sequences = []

# Loop over the records and save the id and sequence data
for seq_record in records:
    descriptions.append(seq_record.id)
    sequences.append(str(seq_record.seq))

# Create a dataframe
df22 = pd.DataFrame({"description": descriptions, "sequence": sequences})

# Display the dataframe
df22

,description,sequence
0,fig|6666666.1036481.peg.1,MIKNWLISNTNLPTDVAAQDPTEDNIKEYFSFPVTSIKKTDEIVNS...
1,fig|6666666.1036481.peg.2,MSKEFVRQWLITNGFQGKEGQEIPEMTNEYIKTVSDRYIELYEKVS...
2,fig|6666666.1036481.peg.3,MNTITSTQFNFPGQKSVYYGKVREVYNINNDLLVMIATDRLSAFYV...
3,fig|6666666.1036481.peg.4,MFTYNPELKNIFNLGNQASGKQQTALAMAVLAYAEHIENPSVLINV...
4,fig|6666666.1036481.peg.5,MVLISGGIGITPLLSMLQSQKDYDNQTIWIHSCRNEKVQAFRDEVE...
...,...,...
3010,fig|6666666.1036481.peg.3011,MAVREDHNLIIAITKENNKLYYKNCPLYKKKQSKH
3011,fig|6666666.1036481.peg.3012,MSSFEQFNLPKSLQKSLDELKFVSPTPIQEKSFNVIMSGRDVMGIA...
3012,fig|6666666.1036481.peg.3013,MTDEVDEMLNDYFDFPEEVTLAKSGTPLEKIEQLSYHVPNFNTKVN...
3013,fig|6666666.1036481.peg.3014,MLAQEILSESFQLNNNALKSKAYLILGSNFTEFANTKKAKDYFLKS...
3014,fig|6666666.1036481.peg.3015,MYQRLSKFAQKFIKPSIFLKYGFNLSPMYRRSTARVMYISENLKNI...

In [28]:
import pandas as pd

# List to store all the dataframes
dataframes = []

# Loop through the range of dataframe names
for i in range(1, 23):
    # Get the dataframe name dynamically using f-string
    df_name = f"df{i}"
    # Assuming the dataframes are already defined with the respective names
    # Add the dataframe to the list
    dataframes.append(locals()[df_name])

# Concatenate all the dataframes in the list
fcovae_df = pd.concat(dataframes)

# Reset the index of the new dataframe
fcovae_df = fcovae_df.reset_index(drop=True)
fcovae_df

,description,sequence
0,WP_008253902.1,MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1,WP_014164161.1,MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2,WP_014164206.1,MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
3,WP_014164231.1,MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
4,WP_014164268.1,MPKMKTKSSAKKRFKVTGSGKIKRKHAFKSHILTKKSKKRKLALTH...
...,...,...
69957,fig|6666666.1036481.peg.3011,MAVREDHNLIIAITKENNKLYYKNCPLYKKKQSKH
69958,fig|6666666.1036481.peg.3012,MSSFEQFNLPKSLQKSLDELKFVSPTPIQEKSFNVIMSGRDVMGIA...
69959,fig|6666666.1036481.peg.3013,MTDEVDEMLNDYFDFPEEVTLAKSGTPLEKIEQLSYHVPNFNTKVN...
69960,fig|6666666.1036481.peg.3014,MLAQEILSESFQLNNNALKSKAYLILGSNFTEFANTKKAKDYFLKS...
69961,fig|6666666.1036481.peg.3015,MYQRLSKFAQKFIKPSIFLKYGFNLSPMYRRSTARVMYISENLKNI...

In [29]:
# Add the ID column with values in the desired format
fcovae_df.insert(0, "id", [f"seq{i}" for i in range(1, len(fcovae_df) + 1)])

# Print the updated dataframe
fcovae_df

,id,description,sequence
0,seq1,WP_008253902.1,MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1,seq2,WP_014164161.1,MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2,seq3,WP_014164206.1,MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
3,seq4,WP_014164231.1,MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
4,seq5,WP_014164268.1,MPKMKTKSSAKKRFKVTGSGKIKRKHAFKSHILTKKSKKRKLALTH...
...,...,...,...
69957,seq69958,fig|6666666.1036481.peg.3011,MAVREDHNLIIAITKENNKLYYKNCPLYKKKQSKH
69958,seq69959,fig|6666666.1036481.peg.3012,MSSFEQFNLPKSLQKSLDELKFVSPTPIQEKSFNVIMSGRDVMGIA...
69959,seq69960,fig|6666666.1036481.peg.3013,MTDEVDEMLNDYFDFPEEVTLAKSGTPLEKIEQLSYHVPNFNTKVN...
69960,seq69961,fig|6666666.1036481.peg.3014,MLAQEILSESFQLNNNALKSKAYLILGSNFTEFANTKKAKDYFLKS...
69961,seq69962,fig|6666666.1036481.peg.3015,MYQRLSKFAQKFIKPSIFLKYGFNLSPMYRRSTARVMYISENLKNI...

In [30]:
fcovae_df.to_csv("fcovae_df_description.csv", index=False)

In [31]:
# Drop the description column
fcovae_df = fcovae_df.drop("description", axis=1)
fcovae_df

             id                                           sequence
0          seq1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1          seq2  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2          seq3  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
3          seq4  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
4          seq5  MPKMKTKSSAKKRFKVTGSGKIKRKHAFKSHILTKKSKKRKLALTH...
...         ...                                                ...
69957  seq69958                MAVREDHNLIIAITKENNKLYYKNCPLYKKKQSKH
69958  seq69959  MSSFEQFNLPKSLQKSLDELKFVSPTPIQEKSFNVIMSGRDVMGIA...
69959  seq69960  MTDEVDEMLNDYFDFPEEVTLAKSGTPLEKIEQLSYHVPNFNTKVN...
69960  seq69961  MLAQEILSESFQLNNNALKSKAYLILGSNFTEFANTKKAKDYFLKS...
69961  seq69962  MYQRLSKFAQKFIKPSIFLKYGFNLSPMYRRSTARVMYISENLKNI...

[69962 rows x 2 columns]

In [32]:
fcovae_df.to_csv("fcovae_df.csv", index=False)